// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PayYourChart.Module.Item;

#nullable disable

namespace PayYourChart.Module.Item.Data.Migrations
{
    [DbContext(typeof(EfItemContext))]
    [Migration("20240504154429_SeedAndDescription")]
    partial class SeedAndDescription
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.4");

            modelBuilder.Entity("PayYourChart.Module.Item.Item", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemCode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<decimal>("Price")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ItemCode")
                        .IsUnique();

                    b.ToTable("Item");

                    b.HasData(
                        new
                        {
                            Id = 1L,
                            Description = "Speech/hearing therapy",
                            ItemCode = "92507",
                            Price = 500.25m
                        },
                        new
                        {
                            Id = 2L,
                            Description = "Use of speech device service",
                            ItemCode = "92609",
                            Price = 205.75m
                        },
                        new
                        {
                            Id = 3L,
                            Description = "Cardiac rehab",
                            ItemCode = "93797",
                            Price = 12345.67m
                        },
                        new
                        {
                            Id = 4L,
                            Description = "Cardiac rehab/monitor",
                            ItemCode = "93798",
                            Price = 789.10m
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
